#!/usr/bin/env node
// Injecte le plan d'entraînement (76 séances, 10 août -> 8 novembre 2026) dans ton appli déployée.
// Planning fixe : Lundi = salle, Mardi = course, Jeudi = repos. Reste réparti sur les jours libres.
// Usage : node seed-plan.mjs https://TON-SITE.netlify.app

const baseUrl = process.argv[2];
if (!baseUrl) {
  console.error("Usage: node seed-plan.mjs https://ton-site.netlify.app");
  process.exit(1);
}

const plan = [
  {
    "sport": "muscu",
    "date": "2026-08-10",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 40,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou (quadriceps/fessiers) + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-08-11",
    "type": "Course — Reprise",
    "distance": 5,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing très facile — écoute stricte du genou, stop si douleur",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-08-12",
    "type": "Vélo salle",
    "distance": null,
    "duree": 45,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — endurance facile",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-08-14",
    "type": "Salle — complément",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément — haut du corps + mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-08-15",
    "type": "Course — Reprise",
    "distance": 5,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile, alterne marche/course si besoin (5x 4min course/1min marche)",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-08-16",
    "type": "Sortie longue",
    "distance": 6,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue très facile, aucune contrainte d'allure",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-08-17",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 40,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-08-18",
    "type": "Course — Reprise",
    "distance": 5,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-08-19",
    "type": "Vélo salle",
    "distance": null,
    "duree": 45,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — endurance facile",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-08-21",
    "type": "Salle — complément",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément — haut du corps + mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-08-22",
    "type": "Course — Reprise",
    "distance": 6,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-08-23",
    "type": "Sortie longue",
    "distance": 8,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue facile, allure conversationnelle",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-08-24",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 40,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-08-25",
    "type": "Course — Reprise",
    "distance": 6,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-08-26",
    "type": "Vélo salle",
    "distance": null,
    "duree": 45,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — endurance facile",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-08-28",
    "type": "Salle — complément",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément — haut du corps + mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-08-29",
    "type": "Course — Reprise",
    "distance": 6,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile + 4x20sec accélérations légères en fin de séance",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-08-30",
    "type": "Sortie longue",
    "distance": 10,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue facile",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-08-31",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 40,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-01",
    "type": "Course — Base",
    "distance": 7,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-09-02",
    "type": "Vélo salle",
    "distance": null,
    "duree": 45,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — endurance",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-09-04",
    "type": "Salle — complément",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément — haut du corps + mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-05",
    "type": "Course — Base",
    "distance": 7,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing + 6x30sec accélérations progressives",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-06",
    "type": "Sortie longue",
    "distance": 12,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue facile",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-09-07",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 40,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-08",
    "type": "Course — Base",
    "distance": 7,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-09-09",
    "type": "Vélo salle",
    "distance": null,
    "duree": 45,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — endurance",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-09-11",
    "type": "Salle — complément",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément — haut du corps + mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-12",
    "type": "Course — Base",
    "distance": 8,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Fartlek léger : 6x1min rapide / 2min facile",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-13",
    "type": "Sortie longue",
    "distance": 14,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue facile",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-09-14",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 35,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage (allégé)",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-15",
    "type": "Course — Récup",
    "distance": 6,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile — semaine allégée",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-09-16",
    "type": "Vélo salle",
    "distance": null,
    "duree": 45,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — récupération",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-09-18",
    "type": "Salle — complément",
    "distance": null,
    "duree": 25,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément léger — mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-19",
    "type": "Course — Récup",
    "distance": 6,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-20",
    "type": "Sortie longue",
    "distance": 10,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue facile — semaine de récupération",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-09-21",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 40,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-22",
    "type": "Course — Base",
    "distance": 8,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-09-23",
    "type": "Vélo salle",
    "distance": null,
    "duree": 45,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — endurance",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-09-25",
    "type": "Salle — complément",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément — haut du corps + mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-26",
    "type": "Course — Base",
    "distance": 9,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Tempo — 20min à allure semi confortable, encadré de 15min facile",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-27",
    "type": "Sortie longue",
    "distance": 16,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue facile",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-09-28",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 40,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-09-29",
    "type": "Course — Spécifique",
    "distance": 8,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-09-30",
    "type": "Vélo salle",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — récupération active",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-10-02",
    "type": "Salle — complément",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément — haut du corps + mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-03",
    "type": "Course — Spécifique",
    "distance": 10,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "4km facile + 6km à allure marathon (5:00/km) si genou ok",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-04",
    "type": "Sortie longue",
    "distance": 20,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue — 15km facile + 5km à allure marathon en fin de sortie",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-10-05",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 35,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage (allégé)",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-06",
    "type": "Course — Récup",
    "distance": 7,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile — semaine allégée",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-10-07",
    "type": "Vélo salle",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — récupération",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-10-09",
    "type": "Salle — complément",
    "distance": null,
    "duree": 25,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément léger — mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-10",
    "type": "Course — Récup",
    "distance": 8,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-11",
    "type": "Sortie longue",
    "distance": 14,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue facile",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-10-12",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 35,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-13",
    "type": "Course — Spécifique",
    "distance": 8,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-10-14",
    "type": "Vélo salle",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — récupération active",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-10-16",
    "type": "Salle — complément",
    "distance": null,
    "duree": 25,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément — mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-17",
    "type": "Course — Spécifique",
    "distance": 12,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "4km facile + 8km à allure marathon",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-18",
    "type": "Sortie longue",
    "distance": 26,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue — 16km facile + 10km finaux à allure marathon",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-10-19",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 35,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-20",
    "type": "Course — Spécifique",
    "distance": 8,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-10-21",
    "type": "Vélo salle",
    "distance": null,
    "duree": 30,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — récupération active",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-10-23",
    "type": "Salle — complément",
    "distance": null,
    "duree": 25,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Complément — mobilité",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-24",
    "type": "Course — Spécifique",
    "distance": 10,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Tempo — 30min à allure semi",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-25",
    "type": "Sortie longue",
    "distance": 30,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie longue la plus longue de la préparation — allure modérée",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-10-26",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 25,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Renfort genou léger + gainage",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-27",
    "type": "Course — Affûtage",
    "distance": 8,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "3km facile + 15min à allure marathon + reste facile",
    "status": "planifie"
  },
  {
    "sport": "velo",
    "date": "2026-10-28",
    "type": "Vélo salle",
    "distance": null,
    "duree": 25,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Vélo salle — récupération très légère",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-10-30",
    "type": "Salle — complément",
    "distance": null,
    "duree": 20,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Mobilité + gainage léger",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-10-31",
    "type": "Course — Affûtage",
    "distance": 6,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing facile",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-11-01",
    "type": "Sortie longue",
    "distance": 14,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Sortie moyenne — 8km facile + 6km à allure marathon, dernier contact avec l'allure",
    "status": "planifie"
  },
  {
    "sport": "muscu",
    "date": "2026-11-02",
    "type": "Salle — renfort genou",
    "distance": null,
    "duree": 20,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Gainage léger uniquement, pas de charge",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-11-03",
    "type": "Course — Course",
    "distance": 5,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing très facile, jambes légères",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-11-04",
    "type": "Footing shakeout",
    "distance": null,
    "duree": 20,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "Footing très léger + 4x20sec accélérations (déjà utilisé le mercredi normalement vélo → ici shakeout)",
    "status": "planifie"
  },
  {
    "sport": "course",
    "date": "2026-11-08",
    "type": "MARATHON",
    "distance": 42.2,
    "duree": null,
    "allure": null,
    "fc": null,
    "ressenti": null,
    "notes": "🏁 MARATHON — objectif 3h30 (5:00/km). Départ prudent, négatif split si possible, écoute ton genou jusqu'au bout.",
    "status": "planifie"
  }
];

async function run() {
  console.log(`Envoi de ${plan.length} séances vers ${baseUrl}/api/workouts ...`);
  let ok = 0, fail = 0;
  for (const session of plan) {
    try {
      const res = await fetch(`${baseUrl}/api/workouts`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(session),
      });
      if (!res.ok) throw new Error(await res.text());
      ok++;
    } catch (err) {
      fail++;
      console.error(`Échec pour ${session.date} (${session.type}):`, err.message);
    }
  }
  console.log(`Terminé : ${ok} séances créées, ${fail} échecs.`);
}

run();
